name: restserver
description: Le serveur d'API REST pour courses3.
version: 3.0.0

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  sse:
    git:
        url: git@github.com:dart-lang/sse.git
        ref: null_safety

dev_dependencies:
  pedantic: ^1.11.0
  http: ^0.13.1
  test: ^1.16.8
  courses_sse_client:
    git: git@github.com:abasty/courses_sse_client.git
